### ISSUE TITLE
Recent version not loading

### ISSUE THREAD

**Issue by mLgz0rn** [tsaavik/Auto-Equipment-Compare#1]
Hey!

I dont know what has changed, but the most recent update of the addon does not seem to load, its not even in the addons list.

Rolling back to previous version works fine

Kind regards

**Comment by tsaavik** [comment]
Thanks so much for pointing this out [mLgz0rn](https://github.com/mLgz0rn)!!
   I've been having some issues with Curse's autobuild and manually pushed this in the meantime. I must have made a mistake. Working on it now!

**Comment by tsaavik** [comment]
Opened a ticket with curseforge about the build issue and manually uploaded a new copy.
I had to remove some of the auto populated fields that the builder uses and make sure the zip filename was correct.
File is accepted, waiting on Curse client to update so I can test end to end

![image](https://github.com/user-attachments/assets/ac574e19-21ff-48a9-9bb5-c66511be3877)

**Comment by tsaavik** [comment]
Okay, all fixed. Manually pushing the build took a few tries to get right!
I also confirmed that /compare still works, seems like some people had trouble with that /shrug
